name: build-test
run-name: ${{ github.actor }} is testing the DAT build
on: [push]
jobs:
  test-DAT-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install -g grunt-cli
      - run: npm run deploy
      - uses: coactions/setup-xvfb@v1
        with:
          run: npm run test
      - uses: "8398a7/action-slack@v4"
        with:
          status: ${{ job.status }}
          fields: "repo,message,commit,author,action,eventName,ref,workflow,job,took,pullRequest"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always() # Pick up events even if the job fails or is canceled.

